SistemaDiscusiones/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'SistemaDiscusiones.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^',include('apps.home.urls')),
    url(r'^',include('apps.users.urls', namespace="users")),
    url(r'^',include('apps.disqus.urls',namespace="disqus")),
    
    #PYTHON SOCIAL
    url(r'',include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/', include(admin.site.urls)),
)

apps/home/urls.py
from django.conf.urls import patterns, include, url
from .views import IndexView

urlpatterns = patterns('',
    url(r'^$' , IndexView.as_view()),
)

apps/users/urls.py
from django.conf.urls import patterns, include, url
from .views import ExtraDataView , UserDetailView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'SistemaDiscusiones.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^log-out/$', 'apps.users.views.LogOut' , name="logout"),
    url(r'^extra-data/$', ExtraDataView.as_view() , name="extra_data"),
    # url mandando el id url(r'^usuario/(?P<pk>[\d]+)/$', UserDetailView.as_view(), name='user_detail'),
 	url(r'^usuario/(?P<slug>[-\w]+)/$', UserDetailView.as_view(), name='user_detail'),
)

apps/home/models.py
from django.db import models

# Create your models here.

apps/home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView , ListView
# Create your views here.
from apps.disqus.models import Question
from apps.users.models import User

class IndexView(ListView):
	template_name = 'home/index.html'
	queryset = Question.objects.all()[:5]

	def get_queryset(self):
		tags = [question.tag.all() for question in self.queryset ]
		return zip(self.queryset,tags)

	def get_context_data(self,**kwargs):
		context = super(IndexView,self).get_context_data(**kwargs)
		context['total_questions']	= Question.objects.count()
		context['total_users'] = User.objects.exclude(is_superuser=True).count()
		return context

templates/home/index.html
{% extends 'base.html' %}

{% load static from staticfiles %}

{% block title %} Devask | Devcode.la{% endblock %}

{% block profile %}

  {% if user.is_authenticated %}

    <ul class="nav navbar-nav navbar-right">
      <li class="contenido-imagen-perfil">
        <a href="#" class="padding-minus">
          <img src="{{user.avatar}}" class="foto-perfil" alt="">
        </a>
      </li>

      <li class="dropdown"><a href="#" class="dropdown-toggle link" data-toggle="dropdown">
         {{user.username}} <b class="caret"></b>
        </a>

         <ul class="dropdown-menu">
          <li><a href="{% url 'users:user_detail' user.username %}">Perfil</a></li>
          <li><a href="{% url 'users:logout' %}">Salir <span class="glyphicon glyphicon-log out"></span></a></li>
        </ul>

      </li>
      
    </ul>
    

  {% endif %}

{% endblock %}

{% block content %}
<div class="container">
                <div class="row cab">
                        <div class="col-md-8 contenido-bienvenida">
                                <div class="jumbotron jumbotron-customize">
                                  <h1>Bienvenidos a DevAsk!</h1>
                                  <p class="subtitulo-jumbotron">El Sistema de Discusiones para Programadores</p>
                                        <p>
                                                <a href="/preguntar/"><button type="button" class="btn btn-primary btn-lg btn-pregunta">Has tu Pregunta!</button></a>
                                        </p>
                                </div>
                        </div>
                        <div class="col-md-4 login">
                                {% if user.is_authenticated %}
                                  <h3>Asocia tu cuenta </h3>  
                                  <p>
                                    {% ifequal backends.not_associated 'facebbok' %}
                                     <a href="{% url 'social:begin' 'twitter' %}" type="button" class="btn btn-primary btn-lg btn-lg-customize-tw"><span class="icon-twitter"></span>Twitter</a>
                                    {% else %}  
                                      <a href="{% url 'social:begin' 'facebook' %}" type="button" class="btn btn-primary btn-lg btn-lg-customize-fb"><span class="icon-facebook"></span>Facebook</a>
                                    {% endifequal %}  
                                  </p>
                                {% else %}
                                    <h3>Conectate con:</h3>
                                    <p>
                                      <a href="{% url 'social:begin' 'facebook' %}" type="button" class="btn btn-primary btn-lg btn-lg-customize-fb"><span class="icon-facebook"></span>Facebook</a>
                                      <a href="{% url 'social:begin' 'twitter' %}" type="button" class="btn btn-primary btn-lg btn-lg-customize-tw"><span class="icon-twitter"></span>Twitter</a>
                                    </p>
                                {% endif %}
                        </div>
                </div>

                <div class="row">
                        <div class="col-md-8 contenido">
                                <ul class="nav nav-pills">
                                  <li class="top">
                                    <a href="#">
                                      Top 5 de Preguntas:
                                    </a>
                                  </li>
                                  <li class="top">
                                    <a href="/preguntas/">
                                      Ver todas las Preguntas:
                                    </a>
                                  </li>
                                  <li >
                                    <a href="#">
                                      <span class="badge pull-right badge-customize">{{ total_questions }}</span>
                                      Preguntas
                                    </a>
                                  </li>
                                  <li >
                                    <a href="#">
                                      <span class="badge pull-right badge-customize">{{ total_users }}</span>
                                      Usuarios
                                    </a>
                                  </li>
                                  <li >
                                    <a href="#">
                                      <span class="badge pull-right badge-customize">42</span>
                                      Home
                                    </a>
                                  </li>
                                </ul>
                                {% for question,tags in object_list %}
                                  <h4><a href="/pregunta/{{ question.slug }}">{{ question.title }}</a> <small>{{ question.user }}</small><span><img src="{{ question.user.avatar }}" class="foto-perfil"></span></h4>
                                  <blockquote class="bloquesito">
                                    <p class="bg-info bg-info-customize">Vistos <span>0</span></p>
                                    <p class="bg-warning bg-info-customize">Respuestas <span>0</span></p>
                                    <p class="bg-success bg-info-customize">Votos <span>0</span></p>
                                    <p class="bg-success bg-fecha-customize">Publicado el: <span>{{ question.modified }}</span></p>
                                    <p class="tags">
                                          <span>Etiquetas:</span>
                                          {% for tag in tags %}
                                            <button type="button" class="btn btn-default btn-xs">{{ tag.nombre }}</button>
                                          {% endfor %}
                                          
                                    </p>
                                  </blockquote>
                                {% endfor %}

                               

                                
                                
                        </div>
                        <div class="col-md-4 contenido-aside" >
                                
                        </div>
                </div>
                
        </div>

{% endblock %}